apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-out
  namespace: es
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: out
    nodePort: 32291
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq
  sessionAffinity: None
  type: NodePort
