server:
  port: 8080
  servlet :
    context-path: /ci
spring:
  application:
    name: jenkins-client
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
    url: jdbc:mysql://0.0.0.0:32309/ci?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  redis:
    host: 0.0.0.0
    port: 36679
    password:
    pool:
      max-active: 200
      max-idle: 10
      max-wait: -1
      min-idle: 0
    timeout: 10000
    repositories:
      enabled: false
  rabbitmq:
    host: 0.0.0.0
    port: 35673
    virtual-host: /devops-dev
    username: devops
    password: password
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        prefetch: 100
  jpa:
    hibernate:
      #update|none
      ddl-auto: update
    show-sql: false
  mail:
    host: 127.0.0.1
    port: 25
    default-encoding: UTF-8
    username: d-fesci
    password: password
    from: xxx@eamil.com
    subject: "(DevOps平台)CI构建报告"
    protocol: smtp
    properties:
      mail:
        smtp:
          timeout: 30000
          connectiontimeout: 10000
  freemarker:
    template-loader-path: file:config/template/
    cache: false
    charset: UTF-8
    suffix: .ftl
  http:
    multipart:
      maxFileSize: 32MB
      maxRequestSize: 32MB
base:
  url: http://0.0.0.0

ci:
  report:
    enable: true
  dingtalk:
    url: https://oapi.dingtalk.com/robot/send?access_token=???
    secret: ??
    accessToken: ??
  harbor:
    url: registryxxxxx
    password: password
  scm:
    user: develop1
    password: password
  k8s-folder: D:/data/k8s-yaml
  hosts: http://ci-ingressxxxxx/
  redis:
    address: ${redis_addr:redis://0.0.0.0:36679}
  storage:
    #typs: local
    type: local

ldap:
  enable: true
  url: "ldap://0.0.0.0:389"
  base: "DC=eazybuilder,DC=com"
  userDn: "xxx@eamil.com"
  userPwd: "xxx"
  referral: ignore
  domainName: "%s@eazybuilder.com"

jenkins:
  url: http://jenkinsxxxxx/jenkins/
  user: admin
  password: password
  home: /var/jenkins_home

maven:
  local_repo: /usr/share/maven-repo
#    local_repo: e:/repository

sonar:
  url: http://sonarqubexxxxx/sonarqube/
  user: sonar
  password: sonar

build:
  docker-host: 0.0.0.0:2375

tool:
  git: http://0.0.0.0:8080/eazybuilder-server/ci-tool.git

qtp:
  agent:
    url: http://ci-qtp-agent:28880/qtp-agent/api/run

selenium:
  agent:
    url: http://ci-selenium-agent:28881/selenium-agent/api/run

appscan:
  agent:
    url: http://ci-appscan-agent:28882/appscan-agent/api/run
message:
  #生产者 需求状态
  ciStatusExchange: ci.status.exchange
  dtpReport: ci.ATSReceive.queue
  ciGuardExchange: ci.guard.exchange
  broadcastExchange: ci.datasync.exchange
  topicExchange: devops.plat.exchange
  fanoutExchange: ci.pipeline.exchange
  queue: ci.pipeline.queue
  routingKey: ci.*
  confirmCallbackBean: eazybuilderRabbitmqConfirmCallbackService
  updateProject: ci.project.update
  returnCallbackBean:
  eazybuilderNotifyFanoutExchange: eazybuilder.notify.exchange
  ciDataSyncExchange: ci.datasync.result.exchange
#统一登录portal

portal:
  used: false
  #统一门户网站的登录地址
  loginUrl: http://upms-web-devxxxxx/#/login?tenantCode=MTAxNzgxNTE2MzIwNzY4
  #验签接口url
  credentialsUrl: ${credentialsUrl:upms-web-devxxxxx/system/cookie}
  #获取用户相关信息
  getUserInfoUrl: ${getUserInfoUrl:upms-web-devxxxxx/system/user/getInfo}
  #获取用户所在的项目组（upms维护的群组信息）
  getProjectGroupUrl: ${getProjectGroupUrl:upms-web-devxxxxx/system/group/user/list/user}
  #获取子系统下当前用户所对应的菜单信息--前端请求，需要使用域名
  getMenusForCurrentUser: ${getMenusForCurrentUser:http://eazybuilder-devops.cn/system/resource/resourceWithMenu}
  #获取用户角色信息
  getRolesById: upms-web-devxxxxx/system/openapi/v1/role/list
  upmsTokenRefresh: false
upms:
  gateway:
    url: "http://upms-web-devxxxxx/system/openapi/v1/"
    token: "Bearer MTAxNzgxNTE2MzIwNzY4"
redmine:
  #流水线部署完默认用户邮箱
  userEmail: xxx@eamil.com
  #流水线部署完默认需求号
  eazybuilderueCode: 0
  #根据当前用户查询项目组
  getProjectsUrl: http://demand-managementxxxxx/demand-management/project/getProjectsByUserName
  #根据项目组查询sprints
  getSprintsUrl: http://demand-managementxxxxx//demand-management/api/sprints/getSprintsByProjectId
  #根据sprint 查询对应的需求
  geteazybuilderuesUrl: http://demand-managementxxxxx/demand-management/api/eazybuilderuesTable/geteazybuilderuesBySprintId
  #根据eazybuilderuesId查询明细
  geteazybuilderuesDetailUrl: http://demand-managementxxxxx/demand-management/api/eazybuilderuesTable/geteazybuilderueById
  #根据sprintsid查询看板信息
  getSprintsById: http://demand-managementxxxxx/demand-management/api/sprints/
#门禁默认值
guard:
  bug_blocker_name: 默认BUG阻断阈值
  bug_blocker_name_thresholdMin: 30
  bug_blocker_name_thresholdMax: 100

  vulner_blocker_name: 默认安全漏洞阻断阈值
  vulner_blocker_name_thresholdMin: 30
  vulner_blocker_name_thresholdMax: 100

  code_smell_blocker_name: 默认编码规范阻断阈值
  code_smell_blocker_name_thresholdMin: 30
  codeSmellBlockerNameThresholdMax: 100

harbor:
  url: https://registryxxxxx
  username: harbor_user
  password: password
  addUserDefaultPwd: defaultPwd
  project:
    ## 默认设定为20GB
    storageLimit: 21474836480
logging:
  level:
    root: info
    com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder: info
    org.hibernate.engine.QueryParameters: info
    org.hibernate.engine.query.HQLQueryPlan: info
eazybuilder:
  cache:
    # CAFFEINE | REDIS
    type: REDIS
    def:
      time-to-live: 2000000
      cache-null-values: false
      key-prefix: global_test
      use-key-prefix: true
      max-Size: 50
    configs:
      customInfoIdCache:
        time-to-live: 2000000
        cache-null-values: true
        key-prefix: custom_info_id
        use-key-prefix: true
        max-Size: 10